### ISSUE TITLE
Slack or Discord? 

### ISSUE THREAD

**Issue by dahifi** [cognosisai/platform#2]
Hello!

 I've been playing around with Temporal and gpt-index, langchain, and been looking at your platform. Just wondering if you have a community server or someplace where I can connect with the devs on this. 

I've basically been trying to build a similar system in Python but just getting started with this tech stack. 

Thanks!

**Comment by mbusigin** [comment]
Hey! Thanks for letting us know. We do have a Slack - here is an invite here: 

https://join.slack.com/share/enQtNDcxMTE3MDkxODY4OS1lYzAxYjg3NTExNjI1ODEwZTdhMzI2YThlNDE2ZGFkOWJiZDY3YTJiODNhYzgyYzY2ZTdkYTNmNTBkZTE4MjY0

**Comment by mbusigin** [comment]
Hey! Thanks for letting us know!

We do have a Slack here: https://join.slack.com/share/enQtNDY5ODU1MzE5NjMyMi0xNWEzMDQ2N2FkOGExZGY0YWQ5NDMxMTIyNDEwOTE3MDZiZWYwNTUyMmZhZDNiNDQxN2MwOGVkMGM0MjljMThl

(fixed)

**Comment by mbusigin** [comment]
This in.
